artifacts_root: artifacts



data_ingestion:
   root_dir : artifacts/data_ingestion
   source_URL: https://github.com/Qurat-17/Deep_learning_project/blob/main/Admission_Predict.zip
   local_data_file: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion
